baseURL = "https://log.birki.io/"
languageCode = "en-us"
title = "log"
theme = "dario"

[params]
  [params.homeInfoParams]
    Title = "log.birki.io"
    Content = "Here is a link:\n - [my website](https://birki.io/)"
    Description = "Default Open Graph Description"

